<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\HospitalSystem.Procurement.Application\HospitalSystem.Procurement.Application.csproj" />
		<ProjectReference Include="..\HospitalSystem.Procurement.Infrastructure\HospitalSystem.Procurement.Infrastructure.csproj" />
		<ProjectReference Include="..\HospitalSystem.WebApi.Common\HospitalSystem.WebApi.Common.csproj" />
	</ItemGroup>

</Project>